Add new program
marekk1992/JavaMasterclass_Section8 pull request #3
Opened 2022-02-18 20:54 UTC by marekk1992

2022-02-19 10:20 UTC, RobertasVainickas requested changes

2022-02-19 10:20 UTC, RobertasVainickas commented on src/exercises/banking/Customer.java
> +        transactions.add(Double.valueOf(transaction));
No need to box transaction manually, autoboxing would work here.

2022-02-19 10:20 UTC, RobertasVainickas commented on src/exercises/banking/Branch.java
> +    public Customer addCustomer(String name) {
addCustomer method after creating new customer does not add it to the list of customers. This does not seem right

2022-02-19 10:20 UTC, RobertasVainickas commented on src/exercises/banking/Branch.java
> +    public void printTransactions(String customerName) {
From method naming I would assume that this method prints all the transactions that belong to this branch.
But from logic I see that you are printing specific customer's transactions. So maybe naming `printCustomerTransactions` would be more specific?

2022-02-19 10:20 UTC, RobertasVainickas commented on src/exercises/banking/Branch.java
> +                System.out.println((i + 1) + " -> " + customers.get(position).getTransactions().get(i));
Now `Branch` class is responsible for writing transactions printing logic. 
Transactions is a concept of Customer class (because transactions is a field in this class). So it seems that all the logic how transactions are printed should reside there. 
I think when user invokes method printCustomerTransactions on specific branch, it should only get the customer, and then ask that customer to print his transactions

2022-02-19 10:20 UTC, RobertasVainickas commented on src/exercises/banking/Bank.java
> +    private ArrayList<Branch> branch = new ArrayList<Branch>();
This variable represents multiple branches not single branch, fix the naming

2022-02-19 10:20 UTC, RobertasVainickas commented on src/exercises/banking/Bank.java
> +    private int indexOfBranch(String name) {
The same comment as for the indexOfCustomer in Branch class.

2022-02-19 10:22 UTC, RobertasVainickas requested changes

2022-02-19 10:22 UTC, RobertasVainickas commented on src/exercises/banking/Bank.java
> +            System.out.println("Branch " + branchName + " has "
Consider if this is responsibility of this class.

2022-02-19 13:57 UTC, marekk1992 commented on src/exercises/banking/Bank.java
> +            System.out.println("Branch " + branchName + " has "
Created method for printing customers in `Branch` class.

2022-02-19 13:58 UTC, marekk1992 commented on src/exercises/banking/Bank.java
> +    private int indexOfBranch(String name) {
Changed return value of method from `int` to `Branch`

2022-02-19 13:58 UTC, marekk1992 commented on src/exercises/banking/Bank.java
> +    private ArrayList<Branch> branch = new ArrayList<Branch>();
Renamed

2022-02-19 13:59 UTC, marekk1992 commented on src/exercises/banking/Branch.java
> +                System.out.println((i + 1) + " -> " + customers.get(position).getTransactions().get(i));
Created method `printCustomersTransactions()` in `Customer `class

2022-02-19 13:59 UTC, marekk1992 commented on src/exercises/banking/Branch.java
> +    public void printTransactions(String customerName) {
Renamed

2022-02-19 13:59 UTC, marekk1992 commented on src/exercises/banking/Branch.java
> +    public Customer addCustomer(String name) {
Fixed

2022-02-19 14:00 UTC, marekk1992 commented on src/exercises/banking/Customer.java
> +        transactions.add(Double.valueOf(transaction));
Fixed

2022-02-19 14:33 UTC, RobertasVainickas requested changes

2022-02-19 14:33 UTC, RobertasVainickas commented on src/exercises/banking/Customer.java
> +    public void printCustomersTransactions() {
I think naming `printTransactions` would be more appropriate here because it is Customer class context so it is not possible to print any other transactions.
From Branch class context, it is good that you named it `printCustomerTransactions` because it is not clear which transactions could be printed there

2022-02-19 14:33 UTC, RobertasVainickas commented on src/exercises/banking/Branch.java
> +        for (Customer customer : customers) {
You already have method getCustomer, which does exactly the same thing as code here: iterates over customers and checks if name matches, so you can just reuse that method, it will be cleaner I think.

2022-02-19 14:33 UTC, RobertasVainickas commented on src/exercises/banking/Branch.java
> +        Customer customer = new Customer(customerName);
I think new Customer should be created only if it does not exist already, but now even if it exists, you would create another one exactly the same Customer.

2022-02-19 14:33 UTC, RobertasVainickas commented on src/exercises/banking/Bank.java
> +    public void printCustomersList(String branchName) {
Maybe `printBranchCustomers()` ?
I think such name would add clarity

2022-02-19 18:44 UTC, marekk1992 commented on src/exercises/banking/Customer.java
> +    public void printCustomersTransactions() {
Renamed

2022-02-19 18:44 UTC, marekk1992 commented on src/exercises/banking/Branch.java
> +        for (Customer customer : customers) {
reused `getCustomer()` method in `addCustomer()` method.

2022-02-19 18:44 UTC, marekk1992 commented on src/exercises/banking/Branch.java
> +        Customer customer = new Customer(customerName);
Fixed

2022-02-19 18:45 UTC, marekk1992 commented on src/exercises/banking/Bank.java
> +    public void printCustomersList(String branchName) {
Renamed

2022-02-19 18:49 UTC, RobertasVainickas approved these changes

2022-03-01 20:53 UTC, marekk1992 commented on src/exercises/playlist/Menu.java
> +    private LinkedList<Song> playlist = new LinkedList<Song>();
Removed playlist from Menu class

2022-03-01 20:55 UTC, marekk1992 commented on src/exercises/playlist/Menu.java
> +    public void addSongToAlbum() {
Smaller methods `createSong` and `addNewSong` created

2022-03-01 20:55 UTC, marekk1992 commented on src/exercises/playlist/Menu.java
> +        ListIterator<Song> listIterator = playlist.listIterator();
fixed

2022-03-01 20:56 UTC, marekk1992 commented on src/exercises/playlist/Menu.java
> +        if (database.addToPlaylist(title)) {
Change return type

2022-03-01 20:57 UTC, marekk1992 commented on src/exercises/playlist/MusicDatabase.java
> +        if (numberOfAlbums == 0) {
fixed

2022-03-01 20:57 UTC, marekk1992 commented on src/exercises/playlist/MusicDatabase.java
> +        for (int i = 0; i < numberOfAlbums; i++) {
fixed

2022-03-01 20:57 UTC, marekk1992 commented on src/exercises/playlist/MusicDatabase.java
> +        for (int i = 0; i < albums.size(); i++) {
fixed

2022-03-02 07:45 UTC, RobertasVainickas requested changes

2022-03-02 07:45 UTC, RobertasVainickas commented on src/exercises/playlist/Menu.java
> +    }
I like the way this method is implemented.
You ask for user input and then delegate adding song to playlist for a database, that way Menu class does not know **how** this song is being added to playlist which is very good, because it is not Menu class responsibility.
Some bad examples of this are methods: `addSongToAlbum, createNewAlbum,` because Menu class has too much knowledge of how song, albums are created/added and this logic should be encapsulated in lower levels. 
**DO NOT FIX THIS IN CURRENT PR**, I just want you to notice such things and completely understand that it is hard to notice such things at this learning phase.

2022-03-02 07:45 UTC, RobertasVainickas commented on src/exercises/playlist/Menu.java
> +    public void openMusicPlayer() {
private

2022-03-02 18:14 UTC, RobertasVainickas approved these changes

2022-03-02 18:20 UTC, merged